name: Arclight Collective
favicon: null
layout_spectrum: 0.7426389567553997
typography_spectrum: 0.23701707017607987
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.17797802900895476
  lightness: 0.9886796793434769
  saturation: 0.1623125073965639
  rhythmicContrast: 0.12498949095606804
purpose: []
